dist: trusty
sudo: false

language:
  - cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - boost1.68
      - libcpprest-dev  

before_script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8

script:
  - mkdir out && cd out
  - cmake -DCCD_BUILD_EXAMPLES=ON -DCCD_BUILD_TESTS=ON ..
  - cmake --build . -- -j $(nproc)

